environment:
  SDL_VIDEODRIVER: dummy
  SDL_AUDIODRIVER: dummy
  SDL_RENDER_DRIVER: software
  matrix:
    - PYTHON: "C:\\Python27"
      PYSDL2_DLL_PATH: "dlls\\32bit"
    - PYTHON: "C:\\Python27-x64"
      PYSDL2_DLL_PATH: "dlls\\64bit"
    - PYTHON: "C:\\Python34"
      PYSDL2_DLL_PATH: "dlls\\32bit"
    - PYTHON: "C:\\Python34-x64"
      PYSDL2_DLL_PATH: "dlls\\64bit"
    - PYTHON: "C:\\Python35"
      PYSDL2_DLL_PATH: "dlls\\32bit"
    - PYTHON: "C:\\Python35-x64"
      PYSDL2_DLL_PATH: "dlls\\64bit"
    - PYTHON: "C:\\Python36"
      PYSDL2_DLL_PATH: "dlls\\32bit"
    - PYTHON: "C:\\Python36-x64"
      PYSDL2_DLL_PATH: "dlls\\64bit"

cache:
  - dlls -> .ci\\install-win-deps.cmd

install:
  - IF NOT EXIST dlls\\32bit\\SDL2.dll .ci\\install-win-deps.cmd
  - "%PYTHON%\\python.exe -m pip install -U pip"
  - "%PYTHON%\\python.exe -m pip install -U numpy"
  - "%PYTHON%\\python.exe -m pip install -U pytest"
  - "%PYTHON%\\python.exe -m pip install ."

build: off

test_script:
  - "%PYTHON%\\python.exe -B -m pytest -v"
